#quarkus.package.fernflower.enabled=true
quarkus.debug.generated-classes-dir=generated-classes
quarkus.debug.transformed-classes-dir=transformed-classes
quarkus.debug.generated-sources-dir=generated-sources-quarkus
